sudo: required
language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
script:
- docker-compose run --rm web bash -c "python wait_for_postgres.py"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/control-prod/web; docker
  push registry.heroku.com/control-prod/web; fi
- if [ "$TRAVIS_BRANCH" == "qa" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
  registry.heroku.com; docker tag web registry.heroku.com/control-qa/web; docker push
  registry.heroku.com/control-qa/web; fi
notifications:
  email: false
cache:
  pip: true
env:
  global:
  - secure: AdzQygLOOTQad9V+HIA5NpQjdBZ3WJ2zbv3U8Dy1XWUsWPGnNI8aNI376ZaRhjQEl7fDeER17Z3Qh4RB548k+XcVSIP9hvILQIGm5NFyTh32MRO/q+WhT0O3u8CwfKUdQ9TeafOgNgyXc1U6pUMaYh7kYrIZ92+gn578E4u9j4/FGOlQugw+0hplORSt4Sr6K0za6wMP4jRm0bFvD6Edqv4SB93UOjoL7piup8K6Qvt0g0AF/BvHvd28P5ZD8p0r6BNq++T2EY0wE5GNereZtxksYwjZ3osQS/07wgb3tgRcJok1XeJO7ypYxhrqj7dxUaOSiRYT2DrNMTi4pLKg6bUw55L81YLgvfoGPKk7jn6lWlWT5lRgkcArNq3i81btiKMdhkFDpAU+Yv4LWeEBr9EK4pImGZEFrPl3PXXHfStkg5ruGifQaYMiJvVxYjNVsQ7At+obccZx98lrxKF75wX69YH+F0sjsvYlnBvdJHMg8lQsldL3ZpjStcl37FwOhxjg89hpkrJWmEcka3lvn7DtFEPlqGPfuybJ88A2AODbh1rmDa/i9sUSlU6K06kOdjpoAwbGF2eKK85fPLjC2kkJZUxFnV4dhuSbbWmzOUK1esvBaSdo4lIdkmyRWNdfxf6FrI5QP7Ne5ATi9Gs3bnOstQkWJDGIRvclUQye+84=
