site_name: control
site_description: manage pulses related to controls
repo_url: https://github.com/mathuv/ctrl
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/mathuv">mathuv</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
